import { BriefType } from "./brief-templates";

interface GenerateBriefOptions {
  briefType: BriefType;
  title: string;
  formData: Record<string, string>;
  project: {
    coupleNames: string;
    weddingDate?: Date | null;
    venueName?: string | null;
    venueLocation?: string | null;
    brandName?: string | null;
    editorName?: string | null;
    editorEmail?: string | null;
    notes?: string | null;
  };
  vendors?: Array<{
    name: string;
    category: string;
    instagramHandle?: string | null;
    website?: string | null;
  }>;
  styleGuide?: {
    editingStyle?: string | null;
    colorPreferences?: string | null;
    musicPreferences?: string | null;
    pacingNotes?: string | null;
    socialCaptionStyle?: string | null;
  } | null;
}

function formatDate(date?: Date | null): string {
  if (!date) return "TBD";
  return new Date(date).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function section(title: string, content: string): string {
  if (!content.trim()) return "";
  return `## ${title}\n\n${content.trim()}\n`;
}

function bulletList(items: string[]): string {
  return items
    .filter((i) => i.trim())
    .map((i) => `- ${i.trim()}`)
    .join("\n");
}

export function generateBriefText(options: GenerateBriefOptions): string {
  const { briefType, title, formData, project, vendors = [], styleGuide } = options;

  const lines: string[] = [];

  // Header
  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`**Brief Type:** ${getBriefTypeLabel(briefType)}`);
  lines.push(`**Generated:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  if (project.brandName) lines.push(`**Studio / Brand:** ${project.brandName}`);
  if (project.editorName) lines.push(`**Editor:** ${project.editorName}${project.editorEmail ? ` (${project.editorEmail})` : ""}`);
  lines.push("");

  // Project Overview
  const overviewItems: string[] = [
    `**Couple:** ${project.coupleNames}`,
    `**Wedding Date:** ${formatDate(project.weddingDate)}`,
    project.venueName ? `**Venue:** ${project.venueName}` : "",
    project.venueLocation ? `**Location:** ${project.venueLocation}` : "",
  ].filter(Boolean);
  lines.push(section("Project Overview", overviewItems.join("\n")));

  // Brief-type-specific content
  switch (briefType) {
    case "WEDDING_FILM":
      lines.push(...generateWeddingFilm(formData, styleGuide));
      break;
    case "HIGHLIGHT_FILM":
      lines.push(...generateHighlightFilm(formData, styleGuide));
      break;
    case "CEREMONY_EDIT":
      lines.push(...generateCeremonyEdit(formData, styleGuide));
      break;
    case "SPEECHES_EDIT":
      lines.push(...generateSpeechesEdit(formData));
      break;
    case "SNEAK_PEEK":
      lines.push(...generateSneakPeek(formData, styleGuide));
      break;
    case "SOCIAL_REEL":
      lines.push(...generateSocialReel(formData, styleGuide));
      break;
    case "TIKTOK":
      lines.push(...generateTikTok(formData));
      break;
    case "VENDOR_PROMO":
      lines.push(...generateVendorPromo(formData));
      break;
    case "PHOTO_CULLING":
      lines.push(...generatePhotoCulling(formData));
      break;
    case "LIGHTROOM_EDITING":
      lines.push(...generateLightroomEditing(formData, styleGuide));
      break;
  }

  // Vendor Credits
  if (vendors.length > 0) {
    const vendorLines = vendors.map((v) => {
      let line = `- **${v.name}** (${v.category})`;
      if (v.instagramHandle) line += ` — Instagram: @${v.instagramHandle.replace("@", "")}`;
      if (v.website) line += ` — ${v.website}`;
      return line;
    });
    lines.push(section("Vendor Credits", vendorLines.join("\n")));
  } else if (formData.vendorTags) {
    lines.push(section("Vendor Credits / Tags", formData.vendorTags));
  }

  // Deadline
  if (formData.deadline) {
    const deadlineContent = [
      `**Deadline:** ${formData.deadline}`,
      formData.deliveryFormat ? `**Delivery Format:** ${formData.deliveryFormat}` : "",
    ].filter(Boolean).join("\n");
    lines.push(section("Delivery & Deadline", deadlineContent));
  }

  // Additional Notes
  if (project.notes || formData.additionalNotes) {
    const notesContent = [project.notes, formData.additionalNotes].filter(Boolean).join("\n\n");
    lines.push(section("Additional Notes", notesContent));
  }

  // Reference Links
  if (formData.referenceLinks) {
    const refs = formData.referenceLinks.split("\n").filter(Boolean);
    if (refs.length > 0) {
      lines.push(section("Reference Links", bulletList(refs)));
    }
  }

  // Footer
  lines.push("---");
  lines.push("*Brief generated by BriefedWed — [briefedwed.com](https://briefedwed.com)*");

  return lines.filter((l) => l !== undefined).join("\n");
}

function generateWeddingFilm(formData: Record<string, string>, styleGuide?: GenerateBriefOptions["styleGuide"]): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Full Wedding Film`,
    formData.targetLength ? `**Target Length:** ${formData.targetLength}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.mustHaveMoments) {
    const items = formData.mustHaveMoments.split("\n").filter(Boolean);
    lines.push(section("Must-Have Moments", bulletList(items)));
  }

  if (formData.avoidMoments) {
    lines.push(section("Do Not Use / Avoid", formData.avoidMoments));
  }

  if (formData.ceremonyNotes) {
    lines.push(section("Ceremony Notes", formData.ceremonyNotes));
  }

  if (formData.receptionNotes) {
    lines.push(section("Reception Notes", formData.receptionNotes));
  }

  const musicContent = [
    formData.musicDirection,
    styleGuide?.musicPreferences ? `*Studio music preferences:* ${styleGuide.musicPreferences}` : "",
  ].filter(Boolean).join("\n\n");
  if (musicContent) lines.push(section("Music & Audio Direction", musicContent));

  const styleContent = [
    formData.pacing ? `**Pacing & Tone:** ${formData.pacing}` : "",
    formData.editingStyle,
    styleGuide?.editingStyle ? `*Studio style guide:* ${styleGuide.editingStyle}` : "",
    styleGuide?.colorPreferences ? `*Color preferences:* ${styleGuide.colorPreferences}` : "",
  ].filter(Boolean).join("\n\n");
  if (styleContent) lines.push(section("Style & Pacing", styleContent));

  if (formData.audioNotes) {
    lines.push(section("Audio Priorities", formData.audioNotes));
  }

  return lines;
}

function generateHighlightFilm(formData: Record<string, string>, styleGuide?: GenerateBriefOptions["styleGuide"]): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Wedding Highlight Film`,
    formData.targetLength ? `**Target Length:** ${formData.targetLength}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.mustHaveMoments) {
    lines.push(section("Must-Have Moments", bulletList(formData.mustHaveMoments.split("\n"))));
  }

  if (formData.openingShot) {
    lines.push(section("Opening Shot / Film Start", formData.openingShot));
  }

  if (formData.avoidMoments) {
    lines.push(section("Moments to Avoid", formData.avoidMoments));
  }

  const musicContent = [
    formData.musicDirection,
    styleGuide?.musicPreferences ? `*Studio preferences:* ${styleGuide.musicPreferences}` : "",
  ].filter(Boolean).join("\n\n");
  if (musicContent) lines.push(section("Music Direction", musicContent));

  const styleContent = [
    formData.pacing ? `**Pacing:** ${formData.pacing}` : "",
    formData.editingStyle,
    styleGuide?.editingStyle ? `*Studio style:* ${styleGuide.editingStyle}` : "",
    styleGuide?.colorPreferences ? `*Color guide:* ${styleGuide.colorPreferences}` : "",
  ].filter(Boolean).join("\n\n");
  if (styleContent) lines.push(section("Style & Color", styleContent));

  if (formData.audioNotes) {
    lines.push(section("Audio Use", formData.audioNotes));
  }

  return lines;
}

function generateCeremonyEdit(formData: Record<string, string>, styleGuide?: GenerateBriefOptions["styleGuide"]): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Ceremony Edit`,
    formData.ceremonyLength ? `**Ceremony Length:** ${formData.ceremonyLength}` : "",
    formData.editingStyle ? `**Editing Style:** ${formData.editingStyle}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.includeElements) {
    lines.push(section("Elements to Include", bulletList(formData.includeElements.split("\n"))));
  }

  if (formData.avoidMoments) {
    lines.push(section("Elements to Exclude", formData.avoidMoments));
  }

  if (formData.vowsAudio) {
    lines.push(section("Audio / Vows Source", formData.vowsAudio));
  }

  const musicContent = [
    formData.musicDirection,
    styleGuide?.musicPreferences ? `*Studio preferences:* ${styleGuide.musicPreferences}` : "",
  ].filter(Boolean).join("\n\n");
  if (musicContent) lines.push(section("Ceremony Music Notes", musicContent));

  if (formData.multicamNotes) {
    lines.push(section("Camera Angles & Multicam Notes", formData.multicamNotes));
  }

  return lines;
}

function generateSpeechesEdit(formData: Record<string, string>): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Speeches & Toasts Edit`,
    formData.targetLength ? `**Target Length:** ${formData.targetLength}` : "",
    formData.subtitles ? `**Subtitles / Captions:** ${formData.subtitles}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.speechOrder) {
    lines.push(section("Speech Order", bulletList(formData.speechOrder.split("\n"))));
  }

  if (formData.trimInstructions) {
    lines.push(section("Editing & Trim Instructions", formData.trimInstructions));
  }

  if (formData.audioNotes) {
    lines.push(section("Audio Notes", formData.audioNotes));
  }

  if (formData.musicDirection) {
    lines.push(section("Background Music", formData.musicDirection));
  }

  return lines;
}

function generateSneakPeek(formData: Record<string, string>, styleGuide?: GenerateBriefOptions["styleGuide"]): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Sneak Peek / Teaser`,
    formData.targetLength ? `**Length:** ${formData.targetLength}` : "",
    formData.aspectRatio ? `**Aspect Ratio:** ${formData.aspectRatio}` : "",
    formData.pacing ? `**Energy Level:** ${formData.pacing}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.mustHaveMoments) {
    lines.push(section("Must-Have Moments (Top Priority)", bulletList(formData.mustHaveMoments.split("\n"))));
  }

  const musicContent = [
    formData.musicDirection,
    styleGuide?.musicPreferences ? `*Studio preferences:* ${styleGuide.musicPreferences}` : "",
  ].filter(Boolean).join("\n\n");
  if (musicContent) lines.push(section("Music Track", musicContent));

  if (formData.endingShot) {
    lines.push(section("Preferred Ending Shot", formData.endingShot));
  }

  if (formData.textOverlay) {
    lines.push(section("Text Overlay / Title Card", formData.textOverlay));
  }

  return lines;
}

function generateSocialReel(formData: Record<string, string>, styleGuide?: GenerateBriefOptions["styleGuide"]): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Instagram Reel`,
    formData.targetLength ? `**Length:** ${formData.targetLength}` : "",
    formData.aspectRatio ? `**Aspect Ratio:** ${formData.aspectRatio}` : "",
    formData.pacing ? `**Cut Pacing:** ${formData.pacing}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.hookMoment) {
    lines.push(section("Opening Hook (First 1–3 Seconds)", formData.hookMoment));
  }

  if (formData.mustHaveMoments) {
    lines.push(section("Must-Have Moments", bulletList(formData.mustHaveMoments.split("\n"))));
  }

  const musicContent = [
    formData.musicDirection,
    styleGuide?.musicPreferences ? `*Studio preferences:* ${styleGuide.musicPreferences}` : "",
  ].filter(Boolean).join("\n\n");
  if (musicContent) lines.push(section("Music / Audio Track", musicContent));

  const captionContent = [
    formData.captionNotes,
    styleGuide?.socialCaptionStyle ? `*Studio caption style:* ${styleGuide.socialCaptionStyle}` : "",
  ].filter(Boolean).join("\n\n");
  if (captionContent) lines.push(section("Caption & On-Screen Text Notes", captionContent));

  if (formData.coverFrame) {
    lines.push(section("Preferred Cover Frame", formData.coverFrame));
  }

  return lines;
}

function generateTikTok(formData: Record<string, string>): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** TikTok`,
    formData.targetLength ? `**Length:** ${formData.targetLength}` : "",
    formData.pacing ? `**Pacing:** ${formData.pacing}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.concept) {
    lines.push(section("TikTok Concept / Angle", formData.concept));
  }

  if (formData.hookMoment) {
    lines.push(section("Opening Hook (First 2–3 Seconds)", formData.hookMoment));
  }

  if (formData.mustHaveMoments) {
    lines.push(section("Key Clips to Include", bulletList(formData.mustHaveMoments.split("\n"))));
  }

  if (formData.musicDirection) {
    lines.push(section("Audio / Sound Track", formData.musicDirection));
  }

  if (formData.textOverlay) {
    lines.push(section("Text Overlays & On-Screen Copy", formData.textOverlay));
  }

  if (formData.avoidMoments) {
    lines.push(section("Moments to Avoid", formData.avoidMoments));
  }

  return lines;
}

function generateVendorPromo(formData: Record<string, string>): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Vendor Promo Clip`,
    formData.vendorName ? `**Vendor:** ${formData.vendorName}` : "",
    formData.vendorCategory ? `**Category:** ${formData.vendorCategory}` : "",
    formData.targetLength ? `**Length:** ${formData.targetLength}` : "",
    formData.aspectRatio ? `**Aspect Ratio:** ${formData.aspectRatio}` : "",
    formData.instagramHandle ? `**Vendor Instagram:** @${formData.instagramHandle.replace("@", "")}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.mustHaveMoments) {
    lines.push(section("Vendor-Specific Moments to Feature", bulletList(formData.mustHaveMoments.split("\n"))));
  }

  if (formData.musicDirection) {
    lines.push(section("Music Direction", formData.musicDirection));
  }

  if (formData.textOverlay) {
    lines.push(section("Text / Branding Overlay", formData.textOverlay));
  }

  return lines;
}

function generatePhotoCulling(formData: Record<string, string>): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Photo Culling Brief`,
    formData.totalImages ? `**Total Images to Cull:** ${formData.totalImages}` : "",
    formData.targetDelivery ? `**Target Delivery Count:** ${formData.targetDelivery}` : "",
    formData.deliveryMethod ? `**Delivery Method:** ${formData.deliveryMethod}` : "",
  ].filter(Boolean).join("\n")));

  if (formData.coverageOrder) {
    lines.push(section("Coverage Priority Order", bulletList(formData.coverageOrder.split("\n"))));
  }

  if (formData.mustIncludeShots) {
    lines.push(section("Must-Include Shot Types", bulletList(formData.mustIncludeShots.split("\n"))));
  }

  if (formData.avoidImages) {
    lines.push(section("Images to Exclude", formData.avoidImages));
  }

  if (formData.duplicateHandling) {
    lines.push(section("Duplicate / Burst Handling", formData.duplicateHandling));
  }

  if (formData.faceCheckPriority) {
    lines.push(section("Face Check & Sharpness Priority", formData.faceCheckPriority));
  }

  if (formData.cameraAngles) {
    lines.push(section("Camera / File Organization Notes", formData.cameraAngles));
  }

  return lines;
}

function generateLightroomEditing(formData: Record<string, string>, styleGuide?: GenerateBriefOptions["styleGuide"]): string[] {
  const lines: string[] = [];

  lines.push(section("Deliverable Requirements", [
    `**Type:** Lightroom Editing Brief`,
    formData.grainTexture ? `**Grain / Film Texture:** ${formData.grainTexture}` : "",
  ].filter(Boolean).join("\n")));

  const presetContent = [
    formData.presetBase,
    styleGuide?.editingStyle ? `*Studio editing style:* ${styleGuide.editingStyle}` : "",
  ].filter(Boolean).join("\n\n");
  if (presetContent) lines.push(section("Preset & Base Style", presetContent));

  if (formData.colorProfile) {
    lines.push(section("Color Science / Camera Profile", formData.colorProfile));
  }

  const colorContent = [
    formData.colorPreferences,
    styleGuide?.colorPreferences ? `*Studio color preferences:* ${styleGuide.colorPreferences}` : "",
  ].filter(Boolean).join("\n\n");
  if (colorContent) lines.push(section("Color Preferences", colorContent));

  if (formData.exposureGuidance) {
    lines.push(section("Exposure Guidance", formData.exposureGuidance));
  }

  if (formData.skinToneNotes) {
    lines.push(section("Skin Tone Notes", formData.skinToneNotes));
  }

  if (formData.blackAndWhite) {
    lines.push(section("Black & White Conversions", formData.blackAndWhite));
  }

  if (formData.lightingAdjustments) {
    lines.push(section("Challenging Lighting Notes", formData.lightingAdjustments));
  }

  if (formData.consistencyNotes) {
    lines.push(section("Gallery Consistency Notes", formData.consistencyNotes));
  }

  if (formData.outputSpecs) {
    lines.push(section("Export / Output Specifications", formData.outputSpecs));
  }

  return lines;
}

function getBriefTypeLabel(type: BriefType): string {
  const labels: Record<BriefType, string> = {
    WEDDING_FILM: "Full Wedding Film",
    HIGHLIGHT_FILM: "Highlight Film",
    CEREMONY_EDIT: "Ceremony Edit",
    SPEECHES_EDIT: "Speeches Edit",
    SNEAK_PEEK: "Sneak Peek / Teaser",
    SOCIAL_REEL: "Instagram Reel",
    TIKTOK: "TikTok",
    VENDOR_PROMO: "Vendor Promo Clip",
    PHOTO_CULLING: "Photo Culling Brief",
    LIGHTROOM_EDITING: "Lightroom Editing Brief",
  };
  return labels[type] || type;
}
