import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { BriefPreview } from "@/components/app/BriefPreview";
import Link from "next/link";
import type { Metadata } from "next";
import { BRIEF_TYPE_LABELS } from "@/lib/brief-templates";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ shareToken: string }>;
}): Promise<Metadata> {
  const { shareToken } = await params;
  const brief = await db.brief.findUnique({
    where: { shareToken },
    include: { project: { select: { coupleNames: true } } },
  });
  if (!brief) return { title: "Brief not found" };

  return {
    title: `${brief.title} — Editor Brief`,
    description: `Wedding post-production brief for ${brief.project.coupleNames}`,
    robots: "noindex",
  };
}

export default async function SharePage({
  params,
}: {
  params: Promise<{ shareToken: string }>;
}) {
  const { shareToken } = await params;
  const brief = await db.brief.findUnique({
    where: { shareToken },
    include: {
      project: {
        select: {
          coupleNames: true,
          weddingDate: true,
          venueName: true,
          brandName: true,
        },
      },
    },
  });

  if (!brief) notFound();

  const typeLabel = BRIEF_TYPE_LABELS[brief.type as keyof typeof BRIEF_TYPE_LABELS] ?? brief.type;

  return (
    <div className="min-h-screen bg-stone-50">
      <header className="bg-white border-b border-stone-200 px-4 py-3">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-sm font-semibold text-stone-700">
            BriefedWed
          </Link>
          <span className="text-xs text-stone-400">Shared brief</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8">
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-stone-900">{brief.title}</h1>
          <div className="flex items-center gap-3 mt-1 flex-wrap">
            <span className="text-sm text-stone-500">{typeLabel}</span>
            <span className="text-stone-300">·</span>
            <span className="text-sm text-stone-500">{brief.project.coupleNames}</span>
            {brief.project.weddingDate && (
              <>
                <span className="text-stone-300">·</span>
                <span className="text-sm text-stone-500">
                  {new Date(brief.project.weddingDate).toLocaleDateString("en-US", {
                    month: "long",
                    day: "numeric",
                    year: "numeric",
                  })}
                </span>
              </>
            )}
            {brief.project.brandName && (
              <>
                <span className="text-stone-300">·</span>
                <span className="text-sm text-stone-500">{brief.project.brandName}</span>
              </>
            )}
          </div>
        </div>

        {brief.generatedText ? (
          <BriefPreview content={brief.generatedText} />
        ) : (
          <div className="text-center py-12 border border-dashed border-stone-300 rounded-xl">
            <p className="text-stone-500">No brief content available.</p>
          </div>
        )}

        <div className="mt-8 pt-6 border-t border-stone-200 text-center">
          <p className="text-sm text-stone-400">
            Generated by{" "}
            <Link href="/" className="text-rose-700 hover:underline">
              BriefedWed
            </Link>{" "}
            — wedding post-production brief builder
          </p>
        </div>
      </main>
    </div>
  );
}
